### ISSUE TITLE
mp-ibc-wavepacket won't compile with Boost version < 1.75

### ISSUE THREAD

**Issue by jesse-osborne** [mptoolkit/mptoolkit#24]
For `mp-ibc-wavepacket`, I use the Jacobi theta function, which is defined in the Boost libraries. It compiles on my machine, but apparently not on GitHub.
```
 mp/mp-ibc-wavepacket.cpp:30:10: fatal error: boost/math/special_functions/jacobi_theta.hpp: No such file or directory
   30 | #include <boost/math/special_functions/jacobi_theta.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I'm not sure why this is failing, since `libboost-all-dev` is installed
https://github.com/ianmccul/mptoolkit-dev/blob/b9a011d4cc89eeca1e668089716af7fe61834515/.github/workflows/build.yml#L19
and the parsers use `<boost/math/special_functions/round.hpp>`, and that doesn't cause any problems when compiling on GitHub.

My justification for using the Jacobi theta function is because you have to convolute with a Gaussian function in momentum space. But just using something like $\exp(-(k-k_0)^2/2\sigma^2)$ is problematic, since $k$ is defined on the periodic domain $[0, 2\pi)$, we want the Gaussian to wrap around properly.

One solution would be to just take $(k-k_0)$ modulo $2\pi$ so it lies in the range $(-\pi,\pi]$, but, especially for large widths $\sigma$, there would be a kink at $k = -k_0$.

This might actually not be much of a problem in practice, but a better solution would be to use a variant of the Gaussian defined on a periodic domain, such as the wrapped Gaussian: https://en.wikipedia.org/wiki/Wrapped_normal_distribution, which is the superposition of an infinite number of Gaussians displaced by $2\pi$: $\sum_j \exp(-(k-k_0+2\pi j)^2/2\sigma^2)$. This sum can be written in terms of the Jacobi theta function, as shown in the Wikipedia article. Intuitively, this seems to be the correct option, since we are working on a lattice and have a periodic momentum space.

Another option is to use the von Mises function: https://en.wikipedia.org/wiki/Von_Mises_distribution, which can be written in terms of elementary functions: $\exp(\cos(k-k_0)/\sigma^2)$.

For small $\sigma$, all three of these options will be pretty much the same, and for this application at least, it might not really matter how smooth the function is at the opposite end of the peak. I think Maarten used the first option (this issue isn't mentioned in the paper).

I also came across the same issue when looking at trapping anyons in a Gaussian potential in the toric code: I oringally used the wrapped Gaussian function, by evaluating the sum for around $j=-10$ to $+10$, but I switched to just taking the modulus of $(k-k_0)$, since that is much easier when passing it to the toolkit parser.

I would expect this issue to come up in condensed matter physics, such as in Wannier functions, which is essentially the same problem as these real-space wavepackets, but I cannot find anything.

**Comment by jesse-osborne** [comment]
To make a long story short, there are two options:

1. Figure out why GitHub can't find this header.
2. Switch to the less ideal Gaussian modulo $2\pi$ or the von Mises distribution.

**Comment by jesse-osborne** [comment]
I think I know the problem now.

I am using Arch Linux on my laptop, so I have the latest version of Boost, but it looks like the Jacobi theta functions were only added in 2020, so the version in Ubuntu doesn't have it yet!

**Comment by ianmccul** [comment]
It looks like jacobi_theta was introduced in boost 1.75, but the current version in ubuntu is 1.74.  I don't have jacobi_theta.hpp on my system.  The configure script checks for a version of boost that is greater than some minimum, currently that is 1.47 although I haven't checked it in a while, there might have been accidentally something that actually depends on a more recent boost than that.

I think depending on a version of boost that isn't in mainstream repositories isn't a good idea.  Current debian has 1.67, for example.  I agree that the theta function looks like a good choice here.  Is it possible to simply copy some code for the theta function into the repo?  That is fine to do as long as it has a compatible license, boost license should be OK.  I'm not sure if the current version of jacobi theta at https://github.com/boostorg/math/blob/62dfa025d7defe55d57bbccb51a1c95eb32418d0/include/boost/math/special_functions/jacobi_theta.hpp is compatible with older boost headers, but you could try it.

**Comment by ianmccul** [comment]
You could do a compile-time check, if the version of boost is >= 1.75 then use the system jacobi functions, otherwise include the version in the repo.

**Comment by jesse-osborne** [comment]
~~What would be the best directory to put `jacobi_theta.hpp` in? I guess a copy of [the license](https://www.boost.org/LICENSE_1_0.txt) also has to be included as well?~~

**Comment by jesse-osborne** [comment]
It looks like `jacobi_theta.hpp` uses headers (`boost/math/tools/complex.hpp`) which are not in the version of Boost on getafix (1.65.1).

So we can either add of the headers needed to make it compile, or I can just make it use a Gaussian mod $2\pi$ if the version of Boost is less than 1.75 (this shouldn't have a huge difference for $\sigma \lesssim 1$, but having a program behave differently depending on the version of Boost is not ideal).

**Comment by jesse-osborne** [comment]
Actually, doing the sum $\sum_j \exp(-(k-k_0+2\pi j)^2/2\sigma^2)$ from $j = -10$ to $+10$ will give the same results for any reasonable sigma, so this is probably the most reasonable workaround for older versions of Boost.

**Comment by ianmccul** [comment]
Ok, that looks like a good solution.

**Comment by ianmccul** [comment]
Indeed, you could probably do up to $j = \pm 100$ and never worry about it ever again.

**Comment by jesse-osborne** [comment]
> Indeed, you could probably do up to j=±100 and never worry about it ever again.

The current workaround calculates the maximum value of j required to get it to machine epsilon, which should be bullet-proof as long as sigma isn't ridiculously large. And if it needs to calculate more than $j=\pm 10000$, it will output a warning.

**Comment by ianmccul** [comment]
that's even better then.  Presumably that is pretty much how the boost function is implemented anyway.
